{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  root-password: {{ .Values.secrets.mysql.rootPassword | quote }}
  username: {{ .Values.secrets.mysql.username | quote }}
  password: {{ .Values.secrets.mysql.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  secret: {{ .Values.secrets.jwt.secret | quote }}
{{- end }}