global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'osgb-backend'
    static_configs:
      - targets: ['osgb-backend-service:5002']
    metrics_path: '/metrics'
    
  - job_name: 'osgb-frontend'
    static_configs:
      - targets: ['osgb-frontend-service:80']
      
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-service:3306']
    metrics_path: '/metrics'