apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'rootpassword' | base64
  root-password: cm9vdHBhc3N3b3Jk
  # echo -n 'osgb_user' | base64
  username: b3NnYl91c2Vy
  # echo -n 'osgb_password' | base64
  password: b3NnYl9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # echo -n 'super_secure_random_key_!@#123' | base64
  secret: c3VwZXJfc2VjdXJlX3JhbmRvbV9rZXlfIUAjMTIz